--
-- Script was generated by Devart dbForge Studio for MySQL, Version 9.2.34.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 8/21/2023 10:17:47 PM
-- Server version: 11.2.0
-- Client version: 4.1
--


SET NAMES 'utf8';


INSERT INTO `misa.web.ntlong`.employee(EmployeeId, EmployeeCode, FullName, DateOfBirth, Gender, IdentityNumber, IdentityDate, IdentityPlace, Email, PhoneNumber, TaxCode, Salary, JoinDate, WorkStatus, PositionId, DeparmentId, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) VALUES
('2158d493-2e73-4432-ad48-f9ae19b240f1', 'nv51', 'nguyen van e', NULL, 1, NULL, NULL, NULL, 'tieulongtu@gmail.com', '123', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('2c5282c1-9ee1-4bc2-b60f-65ecf078578f', 'nv01', 'pham van tuuuu', NULL, NULL, '"', NULL, '"', 'tien@gmail.com', '891271927', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('2df30806-994b-482c-aecf-d8349f220d65', 'nv04', 'pham van tiesdfsdfsn', NULL, NULL, '"', NULL, '"', 'tien@gmail.com', '891271927', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('373edc57-0b95-4757-9c9e-2f065a0a42e4', 'nv04', 'pham van tuuuu', NULL, NULL, '"', NULL, '"', 'tien@gmail.com', '891271927', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('387daa3b-8662-4db7-ab51-f34ba19abf91', 'nv876', 'pham van hoai', NULL, 1, NULL, NULL, NULL, 'tien@gmail.com', '8912719as27', NULL, NULL, NULL, NULL, NULL, NULL, '2023-08-17', 'ntlong', NULL, NULL),
('3d7e7880-c8b4-4ebd-8c05-ce68fcaba60b', 'nv04', 'pham van tiesdfsdfsn', NULL, NULL, '"', NULL, '"', 'tien@gmail.com', '891271927', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('47428c40-211f-420b-9fd1-98713a248b16', 'nv05', 'pham van tuuuu', NULL, NULL, '"', NULL, '"', 'tien@gmail.com', '891271927', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('64305f37-885e-4feb-88e9-94ebec6c2e88', 'nv04', 'pham van tiesdfsdfsn', NULL, NULL, '"', NULL, '"', 'tien@gmail.com', '891271927', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('64ddd230-28a1-43b5-ae10-d85e2080a529', 'nv05', 'pham van tuuuu', NULL, NULL, '"', NULL, '"', 'tien@gmail.com', '891271927', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('6841d4e8-3a7f-11ee-aab9-04d4c477772a', 'nv001', 'Nguyễn thành long', '2023-08-14', 0, '', '2023-08-14', '', '', '', '', 0.0000, '2023-08-14', 0, 'ceb904f9-3a7d-11ee-aab9-04d4c477772a', NULL, NULL, NULL, NULL, NULL),
('6842464f-3a7f-11ee-aab9-04d4c477772a', 'nv002', 'Nguyễn việt anh', '2023-08-14', 0, '', '2023-08-14', '', '', '', '', 0.0000, '2023-08-14', 0, 'cec4d4b4-3a7d-11ee-aab9-04d4c477772a', NULL, NULL, NULL, NULL, NULL),
('73f19ab5-c7b2-4505-956d-8afb5251d272', 'nv856', 'pham van hoai', NULL, 1, NULL, NULL, NULL, 'tien@gmail.com', '8912719as27', NULL, NULL, NULL, NULL, NULL, NULL, '2023-08-17', 'ntlong', NULL, NULL),
('b9258dc5-b446-489d-9caa-a12b42d1b3f5', 'nv04', 'pham van tiesdfsdfsn', NULL, NULL, '"', NULL, '"', 'tien@gmail.com', '891271927', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('c923cd57-7e31-4d14-b414-b9a7cad6002c', 'nv25', 'nguyen thanh long', NULL, 1, NULL, NULL, NULL, 'tieulongtu999@gmail.com', '891271927', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('cf22d45e-d6aa-4332-aaa5-ece2f2b1b52d', 'nv094', 'pham van tien', NULL, NULL, '"', NULL, '"', 'tien@gmail.com', '891271927', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('d6b4068b-d7ca-4dce-99a2-b4dcad21c870', 'nv25', 'nguyen thanh long', NULL, 1, NULL, NULL, NULL, 'tieulongtu999@gmail.com', '891271927', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);


INSERT INTO `misa.web.ntlong`.positions(PositionId, PositionCode, PositionName, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) VALUES
('ceb904f9-3a7d-11ee-aab9-04d4c477772a', 'PB01', 'Phòng Đào tạo', NULL, NULL, NULL, NULL),
('cec4d4b4-3a7d-11ee-aab9-04d4c477772a', 'PB02', 'Phòng Tuyển dụng', NULL, NULL, NULL, NULL),
('cec5dd3d-3a7d-11ee-aab9-04d4c477772a', 'PB03', 'Phòng Sản xuất', NULL, NULL, NULL, NULL);